/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import adminbank.DBConnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author aashirbad JAY
 */
public class test extends javax.swing.JFrame {

    /**
     * Creates new form test
     */
    public test() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf1 = new java.awt.TextField();
        tf2 = new java.awt.TextField();
        button1 = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tf1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        getContentPane().add(tf1);
        tf1.setBounds(359, 51, 211, 78);

        tf2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        getContentPane().add(tf2);
        tf2.setBounds(359, 180, 211, 78);

        button1.setBackground(new java.awt.Color(0, 102, 51));
        button1.setForeground(new java.awt.Color(51, 51, 51));
        button1.setLabel("ooo");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        getContentPane().add(button1);
        button1.setBounds(402, 384, 88, 69);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(828, 137, 154, 80);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(810, 320, 220, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
// log in
       // String n = null ;
        //int i = 0;
        String name=tf1.getText();
        String ID=tf2.getText();
        Connection c;
        try {
            System.out.println("You are ..");
            c = DBConnect.dbConn();
            PreparedStatement s = c.prepareStatement("select * from name1 where name =(?) and ID =(?)");
             
                s.setString(1, name);
                s.setString(2, ID);
                
            ResultSet r = s.executeQuery();
           
            if(r.next())
            {  
                
                JOptionPane.showMessageDialog(null,"Valide");
                
                 String n = r.getString(1);
                 String i = r.getString(2);
                 System.out .println(n +"  " + i);
                 jLabel1.setText(n);
                 jLabel2.setText(i);
                 
            }else
            {
                JOptionPane.showMessageDialog(null,"nnnnnValide"); 
            }
        } catch (Exception e) {
        
       // System.out .println(n + i);
JOptionPane.showMessageDialog(null,"invalid");}
// TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private java.awt.TextField tf1;
    private java.awt.TextField tf2;
    // End of variables declaration//GEN-END:variables
}
