/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminbank;

/**
 *
 * @author aashirbad JAY
 */
public class about extends javax.swing.JFrame {

    /**
     * Creates new form about
     */
    public about() {
        initComponents();
        setLocation(200,150);
        setSize(1500,700);
        jTextPane1.setEditable(false);
        jTextPane1.setText("\tThe Bank of ODISHA  is a commercial bank with headquarters in the Cuttack, Odisha and it is one of the top 5 banks in India. Founded in 2015 been government-owned since nationalisation in 1969. Bank of India has 5100 branches as of 31 January 2017, including 56 offices outside India, which includes five subsidiaries, five representative offices, and one joint venture.\n\n BoO is a founder member of SWIFT (Society for Worldwide Inter Bank Financial Telecommunications), which facilitates provision of cost-effective financialprocessing and communication services.");
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THE BANK OF ODISHA");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(500, 39, 381, 77);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminbank/image/icons8-account-48.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(888, 48, 133, 58);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 0, 883);

        jLabel3.setFont(new java.awt.Font("Yu Gothic Medium", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 0));
        jLabel3.setText("The Bank Of ODISHA");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(430, 10, 400, 60);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminbank/image/icons8-account-48.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(820, 10, 48, 48);

        jTextPane1.setBackground(new java.awt.Color(102, 255, 204));
        jTextPane1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(220, 90, 960, 710);

        jPanel2.setBackground(new java.awt.Color(72, 113, 31));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 220, 800);

        jPanel3.setBackground(new java.awt.Color(72, 113, 31));
        jPanel3.setForeground(new java.awt.Color(255, 153, 102));
        getContentPane().add(jPanel3);
        jPanel3.setBounds(1180, 0, 220, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new about().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
