/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banking.system;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author aashirbad JAY
 */
public class card extends javax.swing.JFrame {

    /**
     * Creates new form card
     */
    public card() {
        initComponents();
        setLocation(400,250);
        setSize(800,470);
        sett();
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LNAME = new javax.swing.JLabel();
        lacc = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(null);

        LNAME.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        LNAME.setForeground(new java.awt.Color(102, 0, 102));
        jPanel1.add(LNAME);
        LNAME.setBounds(160, 280, 320, 40);

        lacc.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lacc.setForeground(new java.awt.Color(0, 153, 153));
        jPanel1.add(lacc);
        lacc.setBounds(320, 210, 250, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("The Bank OF ODISHA");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(310, 110, 320, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 153, 0));
        jLabel4.setText("MASTER CARD");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(120, 200, 320, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banking/system/UserImage/card front.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 30, 574, 322);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new card().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LNAME;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lacc;
    // End of variables declaration//GEN-END:variables

    private void sett() {
       
        try {
            
            Connection c = DBConect.dbConn();
            PreparedStatement p1 = c .prepareStatement("select * from bank01 where acc = ?  ");
            p1.setString(1, LogInUser.AccNo );
            ResultSet r = p1.executeQuery();
            while(r.next()) 
             {   
                LNAME.setText(r.getString("NAME"));
                lacc.setText(LogInUser.AccNo);          
             }
           } 
        catch (Exception e) {
            e.printStackTrace();;
        }
    
    }
}
