/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banking.system;

import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author aashirbad JAY
 */
public class formReg extends javax.swing.JFrame {

    /**
     * Creates new form formReg
     */
    public formReg() {
        initComponents();
        setLocation(400,150);
        setSize(1100,900);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dBConect1 = new banking.system.DBConect();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tname = new java.awt.TextField();
        jLabel2 = new javax.swing.JLabel();
        tfcontact = new java.awt.TextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tmail = new java.awt.TextField();
        tfaadhaar = new java.awt.TextField();
        tfpan = new java.awt.TextField();
        tfaddress = new java.awt.TextField();
        button1 = new java.awt.Button();
        button4 = new java.awt.Button();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jLabel1.setText("Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(230, 140, 197, 29);

        tname.setBackground(new java.awt.Color(102, 102, 102));
        tname.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        tname.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(tname);
        tname.setBounds(460, 140, 293, 34);

        jLabel2.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jLabel2.setText("Addresss");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(220, 210, 197, 29);

        tfcontact.setBackground(new java.awt.Color(102, 102, 102));
        tfcontact.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        tfcontact.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(tfcontact);
        tfcontact.setBounds(460, 350, 293, 34);

        jLabel3.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jLabel3.setText("EMail");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(230, 280, 197, 29);

        jLabel4.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jLabel4.setText("Contact No.");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(220, 350, 197, 29);

        jLabel5.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jLabel5.setText("Aadhaar");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(220, 420, 187, 29);

        jLabel6.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jLabel6.setText("PAN");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(230, 490, 197, 29);

        tmail.setBackground(new java.awt.Color(102, 102, 102));
        tmail.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        tmail.setForeground(new java.awt.Color(204, 204, 204));
        tmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmailActionPerformed(evt);
            }
        });
        jPanel1.add(tmail);
        tmail.setBounds(460, 280, 293, 34);

        tfaadhaar.setBackground(new java.awt.Color(102, 102, 102));
        tfaadhaar.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        tfaadhaar.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(tfaadhaar);
        tfaadhaar.setBounds(460, 420, 290, 34);

        tfpan.setBackground(new java.awt.Color(102, 102, 102));
        tfpan.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        tfpan.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(tfpan);
        tfpan.setBounds(460, 490, 293, 34);

        tfaddress.setBackground(new java.awt.Color(102, 102, 102));
        tfaddress.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        tfaddress.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(tfaddress);
        tfaddress.setBounds(460, 210, 293, 34);

        button1.setBackground(new java.awt.Color(0, 153, 153));
        button1.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        button1.setLabel("RESET");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel1.add(button1);
        button1.setBounds(287, 743, 152, 54);

        button4.setBackground(new java.awt.Color(0, 153, 153));
        button4.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        button4.setLabel("Submit");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        jPanel1.add(button4);
        button4.setBounds(642, 743, 152, 54);

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("G");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(860, 260, 17, 32);

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("I");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(870, 310, 6, 32);

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("T");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(870, 410, 13, 32);

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("E");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(860, 200, 13, 32);

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("R");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(860, 140, 14, 32);

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("R");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(870, 460, 14, 32);

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 153, 153));
        jLabel16.setText("A");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(870, 510, 16, 32);

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 153, 153));
        jLabel17.setText("S");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(870, 360, 13, 32);

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Registration Form");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(230, 20, 580, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 969, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 841, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
// submit 
       // String name = tname.get();
//        if (jpassword1.getText() != jpassword2.getText())
//        {
//            JOptionPane.showMessageDialog(null, "Password is  Not Matched");
//            new formReg().setVisible(true);
//        }

        //String paa = jpassword1.getText();
        //System.err.println("pass" + paa);
       
        try {
            Connection c ;
            c = DBConect.dbConn();
            PreparedStatement p = c.prepareStatement("insert into regform(name,ADDRESS,EMAIL,MOB,AADHAAR,PAN) values (?,?,?,?,?,?)");
            p.setString(1,tname.getText());                                                        // pass delete
            p.setString(2,tfaddress.getText());
            p.setString(3,tmail.getText());
            p.setString(4,tfcontact.getText());
            p.setString(5,tfaadhaar.getText());
            p.setString(6,tfpan.getText());
           // p.setString(7,jpassword1.getText());
           // p.setString(9, paa);
           // p.executeQuery(); 
       /*
          `````````  problem in image insert ````````````````
            
            String location = tfpic.getText();
           
            
            System.out.println(location);

            File f = new File(location);
             FileInputStream fin;
             
             fin = new FileInputStream(location);

            
            p.setBinaryStream(7,fin,fin.available());  
           ``````````````````````````````````````````````````
            */
            
            p.executeQuery();
           // new wait().setVisible(true);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
        JOptionPane.showMessageDialog(null, "Hey , You are Successfully registered !");
        // new wait().setVisible(true);
        
// TODO add your handling code here:
    }//GEN-LAST:event_button4ActionPerformed

    private void tmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tmailActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
// reset
        tfaadhaar.setText(" ");
        tfaddress.setText(" ");
        tfcontact.setText(" ");
        tfpan.setText(" ");
        tmail.setText(" ");
        tname.setText(" ");
        




// TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formReg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button4;
    private banking.system.DBConect dBConect1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private java.awt.TextField tfaadhaar;
    private java.awt.TextField tfaddress;
    private java.awt.TextField tfcontact;
    private java.awt.TextField tfpan;
    private java.awt.TextField tmail;
    private java.awt.TextField tname;
    // End of variables declaration//GEN-END:variables

  
}
